export const data = [
  {
    id: 1,
    name: "page-transition",
    date: "14/12/2020",
    image: `./ProjectImage/images/page_transition.png`,
    href: "https://affectionate-lumiere-f18128.netlify.app/",
    desc: "create react-app with page-transition",
  },
  {
    id: 2,
    name: "pizza-website",
    date: "01/01/2021",
    image: `./ProjectImage/images/pizza.png`,
    href: "#",
    desc: "create react-app pizza-website",
  },
  {
    id: 3,
    name: "login-form",
    date: "28/12/2020",
    image: `./ProjectImage/images/login.png`,
    href: "#",
    desc: "create login form with react",
  },
  {
    id: 4,
    name: "weather-app",
    date: "25/12/2020",
    image: `./ProjectImage/images/weather.png`,
    href: "#",
    desc: "weather app with weather API",
  },
  {
    id: 5,
    name: "Iphone calculator",
    date: "18/01/2021",
    image: `./ProjectImage/images/calc.png`,
    href: "#",
    desc: "Iphone calculator with react",
  },
  {
    id: 6,
    name: "my-potfolio",
    date: "26/01/2021",
    image: `./ProjectImage/images/portfolio_1.png`,
    href: "#",
    desc: "Portfolio website created using react-app",
  },
];
